name: messenger
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  flutter_hooks: ^0.15.0
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  shared_preferences: ^0.5.12+4
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  mqtt_client: ^8.1.0
  uuid: ^2.2.2
  hive_flutter: ^0.3.1
  hive: ^1.4.4+1
  path_provider: ^1.6.27
  firebase_storage: ^7.0.0
  image_picker: ^0.6.7+22
  flutter_image_compress: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: null
  build_runner: null

flutter:

  uses-material-design: true

  assets:
    - flags/

